version: 2.1

jobs:
  build:
    machine: true
    steps:
    - checkout        
    - run:
        name: Log events
        command: journalctl --no-tail --no-pager --merge
        background: true
    - run: sleep 50